import { describe, expect, it } from 'vitest';
import { CARDS, ENEMIES, HEROES, RUNES } from '../src/data';
import { canAttachRune, canTarget, chooseReward, debugAction, discardCard, endTurn, getCardEffect, getCost, initialState, isValidSave, nextBattle, playCard, removeRune, startRun, upgradeCard } from '../src/engine';
import type { CardInstance, GameState, HeroId } from '../src/types';

function add(s: GameState, defId: string, rune?: string): CardInstance { const card = { uid: `test-${++s.serial}`, defId, upgraded: false, rune }; s.cards.push(card); s.hand.push(card.uid); return card; }
function isolated(hero: HeroId = 'warrior') { const s = startRun(hero, 4); s.hand = []; s.deck = s.cards.map(c => c.uid); s.energy = 30; s.enemies.forEach(e => { e.hp = e.maxHp = 200; }); return s; }
function zones(s: GameState) { return [...s.deck, ...s.hand, ...s.discard, ...Object.values(s.gear)]; }
function autoRun(hero: HeroId, seed: number) {
  let s = startRun(hero, seed); let steps = 0;
  while (s.screen !== 'victory' && s.screen !== 'defeat' && steps++ < 500) {
    if (s.screen === 'reward') { const reward = s.hp < s.maxHp * 0.55 ? s.rewards.find(r => r.kind === 'heal') : s.rewards.find(r => r.kind === 'card' && CARDS[r.cardId!].type === 'rune'); s = chooseReward(s, (reward ?? s.rewards[0]).id); continue; }
    if (s.screen === 'progress' || s.screen === 'upgrade') {
      for (const uid of s.cards.filter(c => CARDS[c.defId].type === 'rune').map(c => c.uid)) { const target = s.cards.find(c => !c.rune && canTarget(s, uid, c.uid)); if (target) s = playCard(s, uid, target.uid); }
      while (s.upgradesRemaining > 0) { const target = [...s.cards].sort((a,b) => (getCardEffect(b).damage ?? 0) - (getCardEffect(a).damage ?? 0)).find(c => !c.upgraded && CARDS[c.defId].upgrade); if (!target) break; s = upgradeCard(s, target.uid); }
      s = nextBattle(s); continue;
    }
    let acted = false;
    const ordered = s.hand.map(uid => s.cards.find(c => c.uid === uid)!).sort((a,b) => {
      const score = (c: CardInstance) => { const d = CARDS[c.defId], e = getCardEffect(c); if (d.type === 'rune') return 100; if (d.type === 'equipment') return s.gear[d.slot!] ? -20 : 90; if (e.heal && s.maxHp - s.hp >= e.heal) return 80; return (e.damage ?? 0) * 3 + (e.draw ?? 0) * 9 + (e.shield ?? 0) - getCost(s,c) * 2; }; return score(b) - score(a);
    });
    for (const card of ordered) { if (getCost(s, card) > s.energy) continue; const d = CARDS[card.defId]; let target = 'hero'; if (d.target === 'enemy') target = [...s.enemies].filter(e => e.hp > 0).sort((a,b) => a.hp-b.hp)[0]?.uid ?? ''; if (d.type === 'rune') target = s.hand.find(uid => canTarget(s,card,uid)) ?? ''; const result = playCard(s,card.uid,target); if (result !== s) { s = result; acted = true; break; } }
    if (!acted) { if (s.hand.every(uid => CARDS[s.cards.find(c=>c.uid===uid)!.defId].type === 'rune')) s = discardCard(s,s.hand[0]); s = endTurn(s); }
  }
  return s;
}

describe('data-driven content', () => {
  it('contains the full requested content roster', () => { expect(Object.keys(HEROES)).toHaveLength(2); for (const [type,count] of [['skill',12],['spell',8],['equipment',6],['rune',8]] as const) expect(Object.values(CARDS).filter(c=>c.type===type)).toHaveLength(count); expect(Object.keys(RUNES)).toHaveLength(8); expect(Object.values(ENEMIES).filter(e=>e.tier==='normal')).toHaveLength(5); expect(Object.values(ENEMIES).filter(e=>e.tier==='elite')).toHaveLength(2); expect(Object.values(ENEMIES).filter(e=>e.tier==='boss')).toHaveLength(1); });
});
describe('combat and turns', () => {
  it('starts both heroes at 3 energy with eight cards and five in hand', () => { for (const hero of ['warrior','mage'] as const) { const s = startRun(hero,1); expect(s.cards).toHaveLength(8); expect(s.hand).toHaveLength(5); expect(s.energy).toBe(3); expect(s.hp).toBe(HEROES[hero].hp); } });
  it('discounts only the first warrior Skill and leaves original state untouched', () => { const s = isolated(); const a=add(s,'slash'), b=add(s,'slash'); expect(getCost(s,a)).toBe(0); const n=playCard(s,a.uid,s.enemies[0].uid); expect(getCost(n,b)).toBe(1); expect(s.enemies[0].hp).toBe(200); expect(n.enemies[0].hp).toBe(191); expect(playCard(n,b.uid,'bad')).toBe(n); });
  it('gives Mage bonus only to the first spell and Ring resets each turn', () => { let s=isolated('mage'); const ring=add(s,'mage-ring'), a=add(s,'arcane-bolt'), b=add(s,'arcane-bolt'); s=playCard(s,ring.uid,'hero'); expect(getCost(s,a)).toBe(0); s=playCard(s,a.uid,s.enemies[0].uid); expect(s.enemies[0].hp).toBe(190); expect(getCost(s,b)).toBe(1); s=playCard(s,b.uid,s.enemies[0].uid); expect(s.enemies[0].hp).toBe(182); s=endTurn(s); expect(s.energy).toBe(3); expect(s.firstSpell).toBe(false); });
  it('retains unused cards, refills to five, and recycles without UID duplicates', () => { let s=startRun('warrior',5); const retained=s.hand[0]; s=discardCard(s,s.hand[1]); s=endTurn(s); expect(s.hand).toContain(retained); expect(s.hand).toHaveLength(5); for (let i=0;i<3;i++) { for (const uid of [...s.hand]) s=discardCard(s,uid); s.hp=s.maxHp; s=endTurn(s); } expect(new Set(zones(s)).size).toBe(zones(s).length); expect(s.hand).toHaveLength(5); });
  it('Shield absorbs attack, armor triggers each turn, replacement preserves unique ownership', () => { let s=isolated(); const armor=add(s,'iron-armor'), charm=add(s,'oak-charm'); s=playCard(s,armor.uid,'hero'); expect(s.shield).toBe(5); s=endTurn(s); expect(s.shield).toBe(5); s.energy=30; s=playCard(s,charm.uid,'hero'); expect(s.gear.armor).toBe(charm.uid); expect(s.discard).toContain(armor.uid); expect(new Set(zones(s)).size).toBe(zones(s).length); });
  it('Freeze skips intentions; Burn and Poison tick through Shield and fade', () => { let s=isolated(); s.enemies[0].statuses={ freeze:1,burn:3,poison:2 }; s.enemies[0].shield=99; const hp=s.hp; s=endTurn(s); expect(s.hp).toBe(hp); expect(s.enemies[0].hp).toBe(195); expect(s.enemies[0].statuses).toMatchObject({ freeze:0,burn:2,poison:1 }); });
  it('Weak and Vulnerable modify damage and newly inflicted hero debuffs survive into next player turn', () => { let s=isolated(); const slash=add(s,'slash'); s.statuses.weak=1; s.enemies[0].statuses.vulnerable=2; s=playCard(s,slash.uid,s.enemies[0].uid); expect(s.enemies[0].hp).toBe(190); s.enemies[0].intent={kind:'debuff',label:'weak',status:'weak',stacks:1}; s.statuses={}; s=endTurn(s); expect(s.statuses.weak).toBe(1); });
});

describe('rune modifier lifecycle', () => {
  it('enforces compatibility and prevents replacing or removing a rune in battle', () => { let s=isolated(); const slash=add(s,'slash'), fire=add(s,'rune-fire'), echo=add(s,'rune-echo'), guard=add(s,'guard'); expect(canTarget(s,fire,guard.uid)).toBe(false); s=playCard(s,fire.uid,slash.uid); expect(s.cards.find(c=>c.uid===slash.uid)?.rune).toBe('fire'); expect(s.cards.some(c=>c.uid===fire.uid)).toBe(false); expect(playCard(s,echo.uid,slash.uid)).toBe(s); expect(removeRune(s,slash.uid)).toBe(s); expect(canAttachRune({uid:'x',defId:'cleave',upgraded:false},'chain')).toBe(false); });
  it.each(['fire','power','echo','cheap','blood','chain','frost','renew'])('applies the %s rune behavior', rune => { let s=isolated(); s.hp-=10; const card=add(s,'slash',rune); const hp=s.hp; const before=s.enemies[0].hp; if(rune==='cheap') { s.firstSkill=true; expect(getCost(s,card)).toBe(0); } s=playCard(s,card.uid,s.enemies[0].uid); if(rune==='fire') expect(s.enemies[0].statuses.burn).toBe(2); if(rune==='power') expect(before-s.enemies[0].hp).toBe(13); if(rune==='echo') expect(before-s.enemies[0].hp).toBe(14); if(rune==='blood') { expect(s.hp).toBe(hp-3); expect(before-s.enemies[0].hp).toBe(14); } if(rune==='chain') expect(s.enemies[1].hp).toBe(195); if(rune==='frost') expect(s.enemies[0].statuses.freeze).toBe(1); if(rune==='renew') expect(s.hp).toBe(hp+3); });
  it('weapon runes modify matching offensive cards', () => { let s=isolated(); const sword=add(s,'flame-sword','fire'), slash=add(s,'slash'); s=playCard(s,sword.uid,'hero'); s=playCard(s,slash.uid,s.enemies[0].uid); expect(s.enemies[0].hp).toBe(188); expect(s.enemies[0].statuses.burn).toBe(2); });
  it('Blood pays HP before effects and a lethal payment never activates the card', () => { let s=isolated(); s.hp=3; s.shield=99; const card=add(s,'sunburst','blood'); const enemyHp=s.enemies[0].hp; s=playCard(s,card.uid,s.enemies[0].uid); expect(s.screen).toBe('defeat'); expect(s.hp).toBe(0); expect(s.enemies[0].hp).toBe(enemyHp); expect(s.events).toHaveLength(1); expect(s.events[0]).toMatchObject({kind:'damage',target:'hero',amount:3}); });
  it('Winter on equipment does not stack repeated attacks and skips only one action', () => { let s=isolated(); const sword=add(s,'flame-sword','frost'), a=add(s,'slash'), b=add(s,'slash'); s=playCard(s,sword.uid,'hero'); s=playCard(s,a.uid,s.enemies[0].uid); s=playCard(s,b.uid,s.enemies[0].uid); expect(s.enemies[0].statuses.freeze).toBe(1); const hp=s.hp; s=endTurn(s); expect(s.hp).toBe(hp); expect(s.enemies[0].statuses.freeze).toBe(0); s=endTurn(s); expect(s.hp).toBeLessThan(hp); });
  it('Echo draw reshuffles preserve every UID in exactly one zone', () => { let s=isolated(); const rally=add(s,'rally','echo'); s.discard=[...s.deck]; s.deck=[]; s=playCard(s,rally.uid,'hero'); expect(s.hand).toHaveLength(4); expect(new Set(zones(s)).size).toBe(s.cards.length); expect(zones(s)).toHaveLength(s.cards.length); expect(isValidSave(s)).toBe(true); });
  it('persists attached rune and upgrade across encounters; camp remove/replacement returns the rune', () => { let s=isolated(); const slash=add(s,'slash'), fire=add(s,'rune-fire'); s=playCard(s,fire.uid,slash.uid); s=debugAction(s,'win'); s=chooseReward(s,'reward-rune'); s=upgradeCard(s,slash.uid); expect(s.cards.find(c=>c.uid===slash.uid)?.upgraded).toBe(true); s=nextBattle(s); expect(s.cards.find(c=>c.uid===slash.uid)?.rune).toBe('fire'); s=debugAction(s,'win'); s=chooseReward(s,'reward-rune'); const echo=s.cards.find(c=>c.defId==='rune-echo')!; s=playCard(s,echo.uid,slash.uid); expect(s.cards.find(c=>c.uid===slash.uid)?.rune).toBe('echo'); expect(s.cards.some(c=>c.defId==='rune-fire')).toBe(true); s=removeRune(s,slash.uid); expect(s.cards.find(c=>c.uid===slash.uid)?.rune).toBeUndefined(); expect(s.cards.some(c=>c.defId==='rune-echo')).toBe(true); });
});

describe('run lifecycle and balance', () => {
  it('all cards, equipment and runes are reachable in ordinary rewards across seeds', () => { const seen=new Set<string>(); for(let seed=1;seed<=500;seed++) { let s=startRun(seed%2?'warrior':'mage',seed); for(let fight=0;fight<3;fight++) { s=debugAction(s,'win'); for(const reward of s.rewards) if(reward.cardId) seen.add(reward.cardId); s=chooseReward(s,'reward-card'); if(fight<2) s=nextBattle(s); } } expect([...seen].sort()).toEqual(Object.keys(CARDS).sort()); });
  it('offers exactly three rewards, upgrades once, gives extra upgrade reward, and cannot double claim', () => { let s=debugAction(startRun('warrior',1),'win'); expect(s.rewards).toHaveLength(3); s=chooseReward(s,'reward-rune'); expect(s.screen).toBe('progress'); expect(chooseReward(s,'reward-rune')).toBe(s); const slash=s.cards.find(c=>c.defId==='slash')!; s=upgradeCard(s,slash.uid); expect(getCardEffect(s.cards.find(c=>c.uid===slash.uid)!)).toMatchObject({damage:10}); expect(upgradeCard(s,slash.uid)).toBe(s); s=nextBattle(s); s=debugAction(s,'win'); s=chooseReward(s,'reward-upgrade'); expect(s.upgradesRemaining).toBe(2); });
  it('boss switches visible intention below half HP and defeat/new run work', () => { let s=debugAction(startRun('mage',4),'boss'); s.enemies[0].hp=57; s.energy=99; const bolt=add(s,'arcane-bolt'); s=playCard(s,bolt.uid,s.enemies[0].uid); expect(s.enemies[0].phase).toBe(2); expect(s.enemies[0].intent.label).toContain('Shattered'); s=debugAction(s,'win'); expect(s.screen).toBe('victory'); s=debugAction(startRun('mage',1),'lose'); expect(s.screen).toBe('defeat'); expect(startRun('warrior',2).screen).toBe('battle'); });
  it.each(['warrior','mage'] as const)('can win a complete %s run through normal actions, no debug assistance', hero => { const results=[1,4,8].map(seed=>autoRun(hero,seed)); expect(results.map(s=>({screen:s.screen,hp:s.hp,encounter:s.encounter,turn:s.turn}))).toEqual(expect.arrayContaining([expect.objectContaining({screen:'victory',encounter:3})])); for(const s of results) expect(isValidSave(s)).toBe(true); });
  it('validates saves and rejects malformed values', () => { const s=startRun('mage',1); expect(isValidSave(JSON.parse(JSON.stringify(s)))).toBe(true); expect(isValidSave(null)).toBe(false); expect(isValidSave({...s,cards:[{uid:'bad',defId:'unknown',upgraded:false}]})).toBe(false); expect(isValidSave({...s,hand:['missing']})).toBe(false); expect(isValidSave({...s,events:[null]})).toBe(false); expect(isValidSave({...s,heroId:'toString'})).toBe(false); expect(isValidSave({...s,gear:{weapon:s.hand[0]}})).toBe(false); expect(isValidSave({...s,deck:[...s.deck,s.hand[0]]})).toBe(false); expect(isValidSave({...s,enemies:[{...s.enemies[0],patternIndex:0.5}]})).toBe(false); });
  it('round-trips all eight screens while rejecting broken gear and event payloads', () => { const menu=initialState(), select={...menu,screen:'select' as const}, battle=startRun('warrior',4), reward=debugAction(battle,'win'), progress=chooseReward(reward,'reward-rune'), upgrade={...progress,screen:'upgrade' as const}, victory=debugAction(debugAction(battle,'boss'),'win'), defeat=debugAction(battle,'lose'); expect([menu,select,battle,reward,progress,upgrade,victory,defeat].map(s=>isValidSave(JSON.parse(JSON.stringify(s))))).toEqual(Array(8).fill(true)); for(const gear of [{weapon:'missing'},{armor:battle.hand[0]},{extra:battle.hand[0]},null]) expect(isValidSave({...battle,gear})).toBe(false); for(const events of [[null],[{id:1,target:'hero',kind:'heal',amount:NaN}],[{id:1,target:'hero',kind:'unknown',amount:1}],[{id:1,target:'hero',kind:'status',amount:1,label:{}}]]) expect(isValidSave({...battle,events})).toBe(false); });
});
