import {useEffect,useId,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
type Help={name:string;description:string;value?:string|number;icon?:ReactNode};
// Portal positioning clamps every edge, including zoomed/compact viewports.
export function Tooltip({help,children,className='',interactive=true,focusable=false,label,role}:{help:Help;children:ReactNode;className?:string;interactive?:boolean;focusable?:boolean;label?:string;role?:'img'}) {
 const id=useId(),anchor=useRef<HTMLSpanElement>(null),panel=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),hold=useRef<ReturnType<typeof setTimeout>|null>(null),held=useRef(false),touchPinned=useRef(false),touchOpened=useRef(false),touchStart=useRef({x:0,y:0}),moved=useRef(false);
 const [open,setOpen]=useState(false),[position,setPosition]=useState({left:8,top:8,pointer:20,below:false});
 const close=()=>{touchPinned.current=false;if(timer.current)clearTimeout(timer.current);setOpen(false);};
 const show=()=>{if(touchPinned.current)return;if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setOpen(true),100);};
 useEffect(()=>{if(!open)return;const place=()=>{const a=anchor.current?.getBoundingClientRect(),p=panel.current?.getBoundingClientRect();if(!a||!p)return;const w=innerWidth,h=innerHeight,left=Math.max(8,Math.min(w-p.width-8,a.x+a.width/2-p.width/2));const below=a.top<p.height+18;const top=Math.max(8,Math.min(h-p.height-8,below?a.bottom+10:a.top-p.height-10));setPosition({left,top,pointer:Math.max(12,Math.min(p.width-12,a.x+a.width/2-left)),below});};place();const dismiss=(e:Event)=>{if(!anchor.current?.contains(e.target as Node)&&!panel.current?.contains(e.target as Node))close();};const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('resize',place);window.addEventListener('scroll',close,true);document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',key);return()=>{window.removeEventListener('resize',place);window.removeEventListener('scroll',close,true);document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',key);};},[open]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(hold.current)clearTimeout(hold.current);},[]);
 return <span ref={anchor} className={`tooltip-anchor ${className}`} tabIndex={interactive||focusable?0:undefined} aria-describedby={open?id:undefined} role={role} aria-label={label??(interactive?`${help.name}${help.value!==undefined?' '+help.value:''}. ${help.description}`:undefined)}
 onMouseEnter={show} onMouseLeave={()=>{if(!touchPinned.current)close();}} onFocus={show} onBlur={close}
 onPointerDown={e=>{held.current=false;touchOpened.current=false;moved.current=false;touchStart.current={x:e.clientX,y:e.clientY};if(e.pointerType!=='mouse'&&interactive){touchPinned.current=true;e.stopPropagation();hold.current=setTimeout(()=>{held.current=true;setOpen(true);},350);}}}
 onPointerCancel={()=>{if(hold.current)clearTimeout(hold.current);close();}}
 onPointerMove={e=>{if(e.pointerType!=='mouse'&&Math.hypot(e.clientX-touchStart.current.x,e.clientY-touchStart.current.y)>8){moved.current=true;if(hold.current)clearTimeout(hold.current);}}}
 onPointerUpCapture={e=>{if(hold.current)clearTimeout(hold.current);if(e.pointerType!=='mouse'&&interactive){e.preventDefault();e.stopPropagation();touchOpened.current=true;if(!held.current&&!moved.current)setOpen(v=>{touchPinned.current=!v;return !v;});if(moved.current)close();}}}
 onClick={e=>{if(interactive){e.stopPropagation();if(touchOpened.current||held.current){touchOpened.current=false;held.current=false;return;}setOpen(v=>!v);}}} onKeyDown={e=>{if(interactive&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopPropagation();setOpen(v=>!v);}}}>
 {children}{open&&createPortal(<div ref={panel} id={id} role="tooltip" className={`quest-tooltip ${position.below?'below':'above'}`} style={{left:position.left,top:position.top,'--tip-x':position.pointer+'px'} as CSSProperties}><strong>{help.icon}{help.name}{help.value!==undefined&&<b>{help.value}</b>}</strong><p>{help.description}</p></div>,document.body)}</span>;
}
